// SPDX-License-Identifier: GPL-3.0 

pragma solidity ^0.8.4;


    /*
    
                            Getter
        
        If you have a public state variable of array type, then you can only
        retrieve single elements of the array via the generated getter function.
        This mechanism exists to avoid high gas costs when returning an entire array.
        You can use arguments to specify which individual element to return, for
        example data(0). If you want to return an entire array in one call,
        then you need to write a function, for example:
    
    */
    

contract C {
    
    // Public state variable
    uint[] public myArray;
    
    // Getter function generated by the compiler
    /*
    function myArray(uint i) public view returns(uint) {
        return myArray[i];
    }
    */
    
    // function that returns entire array
    function getArray() public view returns (uint[] memory) {
        return myArray;
    }
    
    // Now you can use getArray() to retrieve the entire array, instead of myArray(i), which returns a single element per call.
    
}
